version: '3'

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
      
    
  otel-collector:
    image: otel/opentelemetry-collector
    ports:
      - "4317:4317"  # For gRPC
      - "55681:55681"  # For HTTP
    command: ["--config=/etc/otel_collector_config.yaml"]
    volumes:
      - ./otel_collector_config.yaml:/etc/otel_collector_config.yaml

  node-chrome:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid
      

networks:
  grid:
    driver: bridge
