receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: "your_exporter_endpoint:4317"  # Adjust to your actual exporter endpoint

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]

